Multiplex requests over a single subscription
nats-io/nats.rs pull request #1069
Opened 2023-08-02 04:00 UTC by caspervonb

2023-08-02 05:35 UTC, caspervonb commented
So we might have to take out inbox on request builder. Or keep legacy requests in for just that scenario.

2023-08-05 05:45 UTC, caspervonb commented
Some benches against main

```

     Running benches/core_nats.rs (target/release/deps/core_nats-9f9b494bfb99583b)
Gnuplot not found, using plotters backend
Benchmarking request amount/32: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.5s.
request amount/32       time:   [673.88 ms 682.44 ms 692.60 ms]
                        thrpt:  [14.438 Kelem/s 14.653 Kelem/s 14.840 Kelem/s]
                 change:
                        time:   [-9.2688% -7.6984% -5.9234%] (p = 0.00 < 0.05)
                        thrpt:  [+6.2964% +8.3405% +10.216%]
                        Performance has improved.
Found 2 outliers among 10 measurements (20.00%)
  1 (10.00%) low mild
  1 (10.00%) high severe
Benchmarking request amount/1024: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.6s.
request amount/1024     time:   [686.72 ms 691.14 ms 695.54 ms]
                        thrpt:  [14.377 Kelem/s 14.469 Kelem/s 14.562 Kelem/s]
                 change:
                        time:   [-9.2669% -8.2935% -7.5109%] (p = 0.00 < 0.05)
                        thrpt:  [+8.1208% +9.0435% +10.213%]
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) low mild
Benchmarking request amount/8192: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 7.4s.
request amount/8192     time:   [769.48 ms 780.60 ms 797.06 ms]
                        thrpt:  [12.546 Kelem/s 12.811 Kelem/s 12.996 Kelem/s]
                 change:
                        time:   [-7.0389% -4.8250% -2.2368%] (p = 0.00 < 0.05)
                        thrpt:  [+2.2879% +5.0696% +7.5719%]
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe

     Running unittests src/lib.rs (target/release/deps/nats-2e00c16348cd9698)

```

2023-08-09 09:30 UTC, Jarema requested changes
Do the TODO :)

2023-08-09 09:30 UTC, Jarema commented on async-nats/src/lib.rs
> +                            sender.send(message).unwrap();
Fix the unwrap.

2023-08-09 10:53 UTC, caspervonb commented on async-nats/src/lib.rs
> +                            sender.send(message).unwrap();
Ups

2023-08-12 12:08 UTC, Jarema requested changes
Looks good!

One change request.

2023-08-12 12:08 UTC, Jarema commented on async-nats/src/lib.rs
> +                } else if let Some(multiplexer) = self.multiplexer.as_mut() {
I would check if sid is as we expect, just to avoid any edge cases.

2023-08-14 18:35 UTC, merged