feat: expose `async_nats::Client::sender` for advanced use cases
nats-io/nats.rs pull request #1267
Opened 2024-05-21 15:46 UTC by rvolosatovs

closes #1266

2024-05-23 16:17 UTC, rvolosatovs commented
Test failure looks unrelated to the PR

2024-07-04 18:10 UTC, Jarema commented
We agreed to implement this, however not directly in the client, but in our extension crate, which will become available very soon. Please stay tuned, we will share more info soon.

2024-08-16 14:48 UTC, rvolosatovs commented
Updated the PR following an offline discussion.
Example usage diff: https://github.com/bytecodealliance/wrpc/pull/244

@caspervonb @Jarema please take a look!

2024-08-20 12:58 UTC, Jarema requested changes
Looks good, but I would rename the `respond` to `reply` for consistency with `Message` (I know our internal name is not consistent, but I prefer consistency in public api if I have to choose one :))

2024-08-20 12:58 UTC, Jarema commented on async-nats/src/client.rs
> +impl Sink<PublishMessage> for Client {
Yeah, those additional fields are making it less straightforward...

I think I prefer `PublishMessage`, but I'm not entirely sure yet.

2024-08-20 19:14 UTC, Jarema approved these changes
LGTM!

2024-08-20 19:40 UTC, merged