De/Serialize `sample_frequency` correctly for Push and Pull Consumers
nats-io/nats.rs pull request #1300
Opened 2024-08-07 13:43 UTC by bengsparks

Closes #1299 

This PR instructs `serde` to rename  `sample_frequency` into `sample_freq` during de/serialization.
It also introduces a module for converting the `u8` into a `String` [due to nats-server's handling of the SampleFrequency field](https://github.com/nats-io/nats-server/blob/d1daf5f7916f088b8ea65c6694ab9b3074f8187b/server/consumer.go#L80).

The PR is split into two separate commits, one for `async-nats` and the other for `nats`, so that the latter can be reverted if it is not wanted.

This PR does not contain any tests, but used the setup from #1299 to check if the field was being correctly set.

2024-08-15 14:47 UTC, bengsparks commented
@caspervonb 
The PR now includes a test in `async-nats/tests/jetstream_tests.rs` that can be executed via `cargo test jetstream::consumer_configs_sample_frequency`, which checks that the cached info of push and pull consumers now contain the correctly set field.
If this PR is given the go-ahead, then I'll revert the commit for the `nats` module and open a second PR.

2024-08-17 08:52 UTC, Jarema requested changes
This looks good @bengsparks !

Please remove the sync nats from this PR and it is good to merge.

2024-08-19 11:17 UTC, bengsparks commented
@Jarema I've reverted the commit that uses the `nats` module. 
I had to fumble around with the commit history a bit (might've accidentally included a commit from another contributor?), but this should be fine to merge.

2024-08-21 05:54 UTC, Jarema approved these changes
LGTM!

Thank you for your contribution!

2024-08-21 10:42 UTC, merged