fix bug: adding back prefix in service group creation
nats-io/nats.rs pull request #1339
Opened 2024-11-05 11:37 UTC by rexf

fix bug: adding back prefix in service group creation

Currently, the prefix will be missing if we are creating group from group.
e.g.
```
let sg = service.group("level1");
sg.endpoint("endpoint1") ==> we can expect to see "level1.endpoint1"

let g2 = sg.group("level2);
g2.endpoint("endpoint2") ==> now we will see "level2.endpoint"
```
this patch is to fix and apply the prefix for the g2 endpoint such that the topic will become
`level1.level2.endpoint2`

2024-11-12 15:47 UTC, rexf commented on async-nats/src/service/mod.rs
> +            prefix: format!("{}.{}", self.prefix.to_string(), prefix.to_string()),
updated

2024-11-13 08:15 UTC, Jarema commented
Hm, I' not a fan of adding a test that starts a server in a unit test and we do not use this pattern across the client, but I can refactor it later myself based on your test, as you already did a lot.

Please fix fmt and it's good to merge.

2024-11-13 08:19 UTC, Jarema requested changes
Please fix fmt.

2024-11-13 08:29 UTC, rexf commented
Thansk Jarema, cargo fmt applied.

2024-11-13 09:11 UTC, Jarema approved these changes
LGTM!

Thanks for your contribution!

2024-11-13 09:11 UTC, merged