improve test server
nats-io/nats.rs pull request #262
Opened 2021-11-19 04:18 UTC by caspervonb

- Rename util module to nats_server
- Return a result from run server helpers
- Reorganize server helpers

2021-11-19 17:41 UTC, derekcollison reviewed
Why the Result and all of those unwraps? What does that buy us?

2021-11-21 15:46 UTC, caspervonb commented
> Why the Result and all of those unwraps? What does that buy us?

Composability and stack traces pointing to the correct lines (which means quickfix list and things like that can jump to it).
If you panic somewhere deep in a utility your test failures are going to look like this:

```
failures:

---- two_connections stdout ----
thread 'two_connections' panicked at 'Oh no!', tests/nats_server/mod.rs:122:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- drop_flushes stdout ----
thread 'drop_flushes' panicked at 'Oh no!', tests/nats_server/mod.rs:122:5

---- async_subscription_drop stdout ----
thread 'async_subscription_drop' panicked at 'Oh no!', tests/nats_server/mod.rs:122:5
```

If you unwrap, that panics at the call site which is what you'd want in a test:

```
failures:

---- jetstream_publish stdout ----
thread 'jetstream_publish' panicked at 'Oh no!', tests/jetstream.rs:51:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2021-11-23 08:03 UTC, Jarema requested changes

2021-11-23 08:03 UTC, Jarema commented on tests/auth_tls.rs
>  fn basic_tls() -> io::Result<()> {
Remove the `Result` if we're using unwrap.

2021-11-23 08:03 UTC, Jarema commented on tests/drop.rs
>  fn drop_flushes() -> io::Result<()> {
Remove the `Result` if we're using unwrap.

2021-11-23 08:03 UTC, Jarema commented on tests/drop.rs
>  fn two_connections() -> io::Result<()> {
Remove the `Result` if we're using unwrap.

2021-11-23 08:03 UTC, Jarema commented on tests/drop.rs
>  fn async_subscription_drop() -> io::Result<()> {
Remove the `Result` if we're using unwrap.

2021-11-23 08:03 UTC, Jarema commented on tests/jetstream.rs
>  fn jetstream_create_stream_and_consumer() -> io::Result<()> {
Remove the `Result` if we're using unwrap.

2021-11-23 08:03 UTC, Jarema commented on tests/jetstream.rs
>  fn jetstream_queue_process() -> io::Result<()> {
Remove the `Result` if we're using unwrap.

2021-11-23 08:03 UTC, Jarema commented on tests/jetstream.rs
>  fn jetstream_basics() -> io::Result<()> {
Remove the `Result` if we're using unwrap.

2021-11-23 08:03 UTC, Jarema commented on tests/auth_nkey.rs
> -    let s = util::run_server("tests/configs/nkey.conf");
Remove the `Result` if we're using unwrap.

2022-01-16 14:16 UTC, caspervonb commented
Became quite stale, faster to redo it.
Closing without merge.

2022-01-16 14:16 UTC, closed without merging