Implement object store
nats-io/nats.rs pull request #269
Opened 2021-11-28 09:44 UTC by caspervonb

- Add support for push-consumer subscriptions
- Implement key-value store
- Implement object store

2021-12-05 15:07 UTC, caspervonb commented on src/jetstream_object.rs
> +        let maybe_message = self.subscription.try_next();
Can overflow, keep a buffer of remaining bytes.

2021-12-07 06:59 UTC, Jarema requested changes

2021-12-07 07:18 UTC, caspervonb commented on src/jetstream_object.rs
> +        if !self.connection.is_server_compatible_version(2, 6, 2) {
Still only 2, error message is different 😁

2021-12-07 07:23 UTC, caspervonb commented on src/jetstream_object.rs
> +#[derive(Debug, Default, Clone, Serialize, Deserialize)]
Did an extra pass on docs this morning, stale 🙂

2021-12-07 07:23 UTC, caspervonb commented on src/jetstream_object.rs
> +            return Err(io::Error::new(io::ErrorKind::Other, "invalid object name"));
SGTM, done.

2021-12-07 07:25 UTC, Jarema commented on src/jetstream_object.rs
> +        if !self.connection.is_server_compatible_version(2, 6, 2) {
I was wondering if you will bring up this argument, or agree that message can be arg to the abstracted code 😄 .

Though expecting an argument that we don't need such abstraction if we only have two error messages (reading your mind), let's leave that like it is until few more cases with more messages will surface.

2021-12-07 07:28 UTC, Jarema approved these changes

2021-12-07 07:31 UTC, merged