Fix jetstream PagedIterator infinite loop
nats-io/nats.rs pull request #589
Opened 2022-08-03 13:57 UTC by kaizensparc

On current nats server version (2.8) when a paged request is made to jetstream (e.g. to list the stream names), the page will never be empty, making the last page being repeated over and over and hanging if callingcollect() on it.

This fix implements the same fix as [jsm.go(5a418c) manager.go +236](https://github.com/nats-io/jsm.go/blob/5a418c85744e080d40ae7c127abdbced9afa5eed/manager.go#L236) by stopping when detecting it's the last page.

2022-12-27 09:25 UTC, Jarema commented
@kaizensparc are you still interested in this PR?
I forgot about it for some time, sorry.

2022-12-30 22:36 UTC, kaizensparc commented
Hello, 
Yes please :)
No problem

2023-01-02 21:31 UTC, Jarema requested changes
Small changes.

2023-01-02 21:31 UTC, Jarema commented on nats/src/jetstream/mod.rs
> +        if page.total <= page.limit + page.offset {
We should check for:
`if page.items.len() + page.offset >= page.total`

2024-09-04 10:11 UTC, Jarema commented
Closing, as this is tale PR with unaddressed review on now deprecated sync client.

2024-09-04 10:11 UTC, closed without merging