Jarema/use direct in kv
nats-io/nats.rs pull request #651
Opened 2022-09-30 09:34 UTC by Jarema

2022-10-01 09:39 UTC, Jarema commented
implements https://github.com/nats-io/nats.rs/pull/651

2022-10-03 13:03 UTC, caspervonb commented on async-nats/src/jetstream/stream.rs
> +        println!("RESPOSNE: {:?}", response);
Take out printlns, use trace or debug?

2022-10-03 13:09 UTC, Jarema commented on async-nats/src/jetstream/stream.rs
> +        println!("RESPOSNE: {:?}", response);
cleanud up those.

2022-10-05 13:49 UTC, caspervonb requested changes

2022-10-05 13:49 UTC, caspervonb commented on async-nats/src/jetstream/response.rs
> +pub struct DirectError {
Hold off on specializing this error for the time being? We'll do all of them together instead.

2022-10-05 13:59 UTC, caspervonb commented on async-nats/src/jetstream/kv/mod.rs
> +                        if de.code == 10037 {
```suggestion
                        // Doc me what this error is
                        if de.code == 10037 {
```

2022-10-10 08:43 UTC, Jarema commented on async-nats/src/jetstream/kv/mod.rs
> +                        if de.code == 10037 {
fixed.

2022-10-13 07:14 UTC, caspervonb approved these changes
lgtm

2022-10-13 08:54 UTC, merged