Add extended purge
nats-io/nats.rs pull request #739
Opened 2022-11-21 19:45 UTC by Jarema

2022-11-22 17:31 UTC, caspervonb commented
I've got a slightly different approach in mind, still using a builder but into_future to make it look like a single async call chain. Will raise a PR shortly.

2022-11-23 15:51 UTC, caspervonb requested changes
Spot on to what I had in mind, digging this! Raising the same for request today 😁

Some nitpicky nits

2022-11-23 15:51 UTC, caspervonb commented on async-nats/tests/jetstream_tests.rs
> +    async fn send_purge() {
```suggestion
    async fn purge() {
```

2022-11-23 15:51 UTC, caspervonb commented on async-nats/src/jetstream/stream.rs
> +pub struct PurgeFuture<SEQUENCE, KEEP>
This isn't the future (yet)

```suggestion
pub struct Purge<SEQUENCE, KEEP>
```

2022-11-23 15:51 UTC, caspervonb commented on async-nats/src/jetstream/stream.rs
> +    stream: crate::jetstream::stream::Stream,
You're in the same scope here?

```suggestion
    stream: Stream,
```

2022-11-23 15:51 UTC, caspervonb commented on async-nats/src/jetstream/stream.rs
> +async fn send_purge_request(stream: Stream, request: PurgeRequest) -> Result<PurgeResponse, Error> {
Inline this inside into_future?

```suggestion
async fn send_purge_request(stream: Stream, request: PurgeRequest) -> Result<PurgeResponse, Error> {
```

2022-11-23 15:51 UTC, caspervonb commented on async-nats/src/jetstream/stream.rs
> +    pub(crate) fn build(stream: Stream) -> PurgeFuture<No, No> {
Subject is always required?

```suggestion
    pub(crate) fn from(stream: Stream, filter: String) -> PurgeFuture<No, No> {
```

2022-11-23 19:33 UTC, Jarema commented on async-nats/src/jetstream/stream.rs
> +    pub(crate) fn build(stream: Stream) -> PurgeFuture<No, No> {
No. You can purge the whole stream.

2022-11-23 20:00 UTC, caspervonb approved these changes
lgtm

2022-11-23 21:59 UTC, merged