Add stream names list
nats-io/nats.rs pull request #783
Opened 2022-12-27 20:39 UTC by Jarema

2022-12-28 15:11 UTC, caspervonb requested changes
Bikeshedding

2022-12-28 15:11 UTC, caspervonb commented on async-nats/src/jetstream/context.rs
> +pub struct StreamNamesList {
```suggestion
pub struct StreamNames {
```

2022-12-28 15:11 UTC, caspervonb commented on async-nats/src/jetstream/context.rs
> +    pub fn list_stream_names(&self) -> StreamNamesList {
```suggestion
    pub fn stream_names(&self) -> StreamNamesList {
```

2022-12-29 09:03 UTC, piotrpio approved these changes
LGTM

2022-12-29 11:24 UTC, caspervonb approved these changes
LGTM.

Remember to squash.

2022-12-29 11:32 UTC, merged